name: PHP Audit

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer, phpstan, psalm, phpcs, phpmd, parallel-lint

      - name: Install deps (dev-only scaffold if none)
        run: |
          if [ ! -f composer.json ]; then
            cat > composer.json <<'JSON'
            {
              "name": "temp/tooling",
              "require-dev": {
                "phpstan/phpstan": "^1.11",
                "vimeo/psalm": "^5.26",
                "squizlabs/php_codesniffer": "^3.10",
                "phpmd/phpmd": "^2.15",
                "php-parallel-lint/php-parallel-lint": "^1.4"
              }
            }
JSON
          fi
          composer install --no-interaction --no-plugins --no-scripts || true

      - name: PHP Lint
        run: parallel-lint --colors --show-deprecated --show-errors-on-success .

      - name: PHPStan (max level)
        continue-on-error: true
        run: phpstan analyse --no-progress --level=max . | tee phpstan.txt

      - name: Psalm
        continue-on-error: true
        run: psalm --output-format=text | tee psalm.txt

      - name: PHPCS (PSR12)
        continue-on-error: true
        run: phpcs --standard=PSR12 --report=full --extensions=php . | tee phpcs.txt

      - name: PHPMD
        continue-on-error: true
        run: phpmd . text cleancode,codesize,controversial,design,naming,unusedcode --suffixes php --exclude vendor | tee phpmd.txt

      - name: Quick security greps
        run: |
          {
            echo "=== POSSIBLE RAW SQL ==="
            grep -RIn --include="*.php" -E "mysqli_query|mysql_query|->query\\(|->exec\\(|PDO::query\\(" . || true
            echo
            echo "=== PASSWORD HANDLING ==="
            grep -RIn --include="*.php" -E "md5\\(|sha1\\(|crypt\\(|password_hash\\(|password_verify\\(" . || true
            echo
            echo "=== FILE UPLOADS ==="
            grep -RIn --include="*.php" -E "\\$_FILES\\[|move_uploaded_file\\(" . || true
            echo
            echo "=== XSS Sinks (check escaping) ==="
            grep -RIn --include="*.php" -E "echo \\$|print \\$|\\$_(GET|POST|REQUEST)" . || true
            echo
            echo "=== CSRF Tokens ==="
            grep -RIn --include="*.php" -E "csrf|CSRF|csrf_token" . || true
            echo
            echo "=== SESSION HARDENING ==="
            grep -RIn --include="*.php" -E "session_start\\(|session_set_cookie_params\\(|ini_set\\(" . || true
          } | tee greps.txt

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: |
            phpstan.txt
            psalm.txt
            phpcs.txt
            phpmd.txt
            greps.txt
          if-no-files-found: warn
